export interface SimpleProduct {
  ID: string;
  Type: string;
  SKU: string;
  Name: string;
  Published: string;
  "Is featured?": string;
  "Visibility in catalog": string;
  "Short description": string;
  Description: string;
  "Date sale price starts": string;
  "Date sale price ends": string;
  "Tax status": string;
  "Tax class": string;
  "In stock?": string;
  Stock: string;
  "Low stock amount": string;
  "Backorders allowed?": string;
  "Sold individually?": string;
  "Weight (kg)": string;
  "Length (cm)": string;
  "Width (cm)": string;
  "Height (cm)": string;
  "Allow customer reviews?": string;
  "Purchase note": string;
  "Sale price": string;
  "Regular price": string;
  Categories: string;
  Tags: string;
  "Shipping class": string;
  Images: string;
  "Download limit": string;
  "Download expiry days": string;
  Parent: string;
  "Grouped products": string;
  Upsells: string;
  "Cross-sells": string;
  "External URL": string;
  "Button text": string;
  Position: string;
}
